devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),

    path('reset_passoword/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"),
         name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"),
         name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"),
         name="password_reset_complete"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views


urlpatterns = [

    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerUser, name='register'),

    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>', views.userProfile, name='user-profile'),

    path('account/', views.userAccount, name='user-account'),
    path('edit-account/', views.editAccount, name='edit-account'),


    path('create-skill/', views.createSkill, name='create-skill'),
    path('update-skill/<str:pk>/', views.updateSkill, name='update-skill'),
    path('delete-skill/<str:pk>/', views.deleteSkill, name='delete-skill'),

    path('inbox/', views.inbox, name='inbox'),
    path('message/<str:pk>/', views.message, name='message'),
    path('create-message/<str:pk>/', views.createMessage, name='create-message'),


]

projects/models.py
from django.db import models
import uuid
from users.models import Profile

# Create your models here.


class Project(models.Model):
    owner = models.ForeignKey(
        Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_imaged = models.ImageField(
        null=True, blank=True, default='default.jpg')
    demo_link = models.CharField(max_length=1000, null=True, blank=True)
    source_link = models.CharField(max_length=1000, null=True, blank=True)
    vote_total = models.IntegerField(default=0)
    vote_ratio = models.IntegerField(default=0)
    tags = models.ManyToManyField('Tag', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-vote_ratio', '-vote_total', 'title']

    @property
    def imageURL(self):
        try:
            img = self.featured_imaged
        except:
            img = ''
        return img

    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list('owner__id', flat=True)

        return queryset

    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value='up').count()
        totalVotes = reviews.count()

        ratio = (upVotes / totalVotes) * 100
        self.vote_total = totalVotes
        self.vote_ratio = ratio
        self.save()


class Review(models.Model):

    VOTE_TYPE = (
        ('up', 'up'),
        ('down', 'down'),
    )

    owner = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True, blank=True)
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, null=True, blank=True)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=50, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    class Meta:
        unique_together = [['owner', 'project']]

    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=500, null=True, blank=True)
    username = models.CharField(max_length=200, null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    short_intro = models.CharField(max_length=500, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    profile_image = models.ImageField(
        null=True, blank=True, upload_to='profiles/', default='profiles/user-default.png')
    social_github = models.CharField(max_length=200, null=True, blank=True)
    social_twitter = models.CharField(max_length=200, null=True, blank=True)
    social_linkedin = models.CharField(max_length=200, null=True, blank=True)
    social_youtube = models.CharField(max_length=200, null=True, blank=True)
    social_website = models.CharField(max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.username)

    class Meta:
        ordering = ['created']

    @property
    def imageURL(self):
        try:
            img = self.profile_image.url
        except:
            img = ''
        return img


class Skill(models.Model):
    owner = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)


class Message(models.Model):
    sender = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name="messages")
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['is_read', '-created']

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, Skill, Message


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            'first_name': 'Name',
        }

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        for k, v in self.fields.items():
            v.widget.attrs.update({'class': 'input'})


class Profileform(ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        super(Profileform, self).__init__(*args, **kwargs)

        for k, v in self.fields.items():
            v.widget.attrs.update({'class': 'input'})


class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = '__all__'
        exclude = ['owner']

    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)

        for k, v in self.fields.items():
            v.widget.attrs.update({'class': 'input'})


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body']

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        for k, v in self.fields.items():
            v.widget.attrs.update({'class': 'input'})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Profile
from .forms import CustomUserCreationForm, Profileform, SkillForm, MessageForm
from .utils import searchUsers, paginateProfiles


# Create your views here.
def loginUser(request):
    page = 'login'

    if request.user.is_authenticated:
        return redirect('profiles')

    if request.method == 'POST':
        username = request.POST['username'].lower()
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(request.GET['next'] if 'next' in request.GET else 'user-account')

        else:
            messages.error(request, 'Bad Credentials')

    context = {'page': page}

    return render(request, 'users/login-register.html', context)


def logoutUser(request):
    logout(request)
    messages.info(request, 'User was logged out!')
    return redirect('login')


def registerUser(request):
    page = 'register'

    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()

            user.save()

            messages.success(request, 'User account was created')

            login(request, user)

            return redirect('edit-account')

        else:
            messages.error(request, 'Error has occurred during registration')

    context = {'page': page, 'form': form}

    return render(request, 'users/login-register.html', context)


def profiles(request):

    profiles, search_query = searchUsers(request)

    custom_range, profiles = paginateProfiles(request, profiles, 6)

    context = {'profiles': profiles, 'search_query': search_query,
               'custom_range': custom_range}

    return render(request, 'users/profiles.html', context)


def userProfile(request, pk):

    profile = Profile.objects.get(id=pk)

    topSkills = profile.skill_set.exclude(description__exact='')
    otherSkills = profile.skill_set.filter(description='')

    context = {'profile': profile, 'topSkills': topSkills,
               'otherSkills': otherSkills}

    return render(request, 'users/user-profile.html', context)


@login_required(login_url='login')
def userAccount(request):

    profile = request.user.profile

    context = {'profile': profile}

    return render(request, 'users/account.html', context)


@login_required(login_url='login')
def editAccount(request):

    profile = request.user.profile

    form = Profileform(instance=profile)

    if request.method == 'POST':
        form = Profileform(request.POST, request.FILES, instance=profile)

        if form.is_valid():
            form.save()

            return redirect('user-account')

    context = {'form': form}

    return render(request, 'users/profile-form.html', context)


@login_required(login_url='login')
def createSkill(request):

    profile = request.user.profile
    form = SkillForm()

    if request.method == 'POST':
        form = SkillForm(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.owner = profile
            skill.save()
            messages.success(request, 'Skill was added successfully')

            return redirect('user-account')

    context = {'form': form, 'action': 'Create'}

    return render(request, 'users/skill-form.html', context)


@login_required(login_url='login')
def updateSkill(request, pk):

    profile = request.user.profile
    skill = profile.skill_set.get(id=pk)

    form = SkillForm(instance=skill)

    if request.method == 'POST':
        form = SkillForm(request.POST, instance=skill)
        if form.is_valid():
            form.save()
            messages.success(request, 'Skill was updated')

            return redirect('user-account')

    context = {'form': form, 'action': 'Update'}

    return render(request, 'users/skill-form.html', context)


@login_required(login_url='login')
def deleteSkill(request, pk):

    profile = request.user.profile
    skill = profile.skill_set.get(id=pk)

    if request.method == 'POST':
        skill.delete()
        messages.success(request, 'Skill was deleted!')

        return redirect('user-account')

    context = {'title': skill.name}

    return render(request, 'delete-template.html', context)


@login_required(login_url='login')
def inbox(request):
    profile = request.user.profile

    messageRequests = profile.messages.all()

    unreadCount = messageRequests.filter(is_read=False).count

    context = {'messageRequests': messageRequests, 'unreadCount': unreadCount}

    return render(request, 'users/inbox.html', context)


@login_required(login_url='login')
def message(request, pk):
    profile = request.user.profile

    message = profile.messages.get(id=pk)

    if message.is_read == False:
        message.is_read = True
        message.save()

    context = {'message': message}

    return render(request, 'users/message.html', context)


def createMessage(request, pk):
    recipient = Profile.objects.get(id=pk)
    form = MessageForm()

    try:
        sender = request.user.profile

    except:
        sender = None

    if request.method == 'POST':
        form = MessageForm(request.POST)

        if form.is_valid():
            message = form.save(commit=False)
            message.sender = sender
            message.recipient = recipient

            if sender:
                message.name = sender.name
                message.email = sender.email

            message.save()

            messages.success(request, 'Message sent!')

            return redirect('user-profile', pk=recipient.id)

    context = {'recipient': recipient, 'form': form}

    return render(request, 'users/message_form.html', context)

users/templates/users/account.html
{% extends 'main.html' %}


{% block body %}

    <main class="settingsPage profile my-md">
        <div class="container">
            <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                <div class="card__body dev">
                    <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-account' %}"><i class="fa-regular fa-pen-to-square"></i> Edit</a>
                    <img class="avatar avatar--xl dev__avatar" src="{{ profile.profile_image.url }}" />
                    <h2 class="dev__name">{{profile.name}}</h2>
                    <p class="dev__title">{{profile.short_intro}}</p>
                    <p class="dev__location">{{profile.location}}</p>
                    <ul class="dev__social">
                        {% if profile.social_github %}
                            <li>
                                <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="fa-brands fa-github fa-2x"></i></a>
                            </li>
                        {% endif %}

                        {% if profile.social_twitter %}
                            <li>
                            <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="fa-brands fa-twitter fa-2x"></i></a>
                            </li>
                        {% endif %}

                        {% if profile.social_linkedin %}
                            <li>
                            <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="fa-brands fa-linkedin fa-2x"></i></a>
                            </li>
                        {% endif %}

                        {% if profile.social_website %}
                            <li>
                            <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="fa-solid fa-globe fa-2x"></i></a>
                            </li>
                        {% endif %}
                    </ul>
                   
                </div>
                </div>
            </div>
            <div class="column column--2of3">
                <div class="devInfo">
                <h3 class="devInfo__title">About Me</h3>
                <p class="devInfo__about">
                    {{profile.bio}}
                </p>
                </div>
                <div class="settings">
                <h3 class="settings__title">Skills</h3>
                <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-skill' %}"><i class="fa-solid fa-plus"></i> Add Skill</a>
                </div>

                <table class="settings__table">
                    {% for skill in profile.skill_set.all %}
                        <tr>
                            <td class="settings__tableInfo">
                            <h4>{{ skill }}</h4>

                            {% if skill.description %}
                            <p>
                                {{skill.description}}
                            </p>
                            {% endif %}
                            </td>
                            <td class="settings__tableActions">
                            <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-skill' skill.id %}"><i class="fa-regular fa-pen-to-square"></i> Edit</a>
                            <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-skill' skill.id %}?next=/account"><i class="fa-solid fa-delete-left"></i>
                                Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                
                </table>

                <div class="settings">
                <h3 class="settings__title">Projects</h3>
                <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-project' %}"><i class="fa-solid fa-plus"></i> Add Project</a>
                </div>

                <table class="settings__table">
                    {% for project in profile.project_set.all %}

                    <tr>
                        <td class="settings__thumbnail">
                        <a href="{% url 'project' project.id %}"><img src="{{project.imageURL.url}}" alt="Project Thumbnail" /></a>
                        </td>
                        <td class="settings__tableInfo">
                        <a href="{% url 'project' project.id %}">{{project.title}}</a>
                        <p>
                           {{project.description|slice:"150"}}
                        </p>
                        </td>
                        <td class="settings__tableActions">
                        <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-project' project.id %}"><i class="fa-regular fa-pen-to-square"></i> Edit</a>
                        <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-project' project.id %}?next=/account"><i class="fa-solid fa-delete-left"></i>
                            Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
               
                </table>
            </div>
            </div>
        </div>
    </main>

{% endblock %}

users/templates/users/inbox.html
{% extends 'main.html' %}

{% block body %}


<main class="inbox my-xl">
    <div class="content-box">
      <h3 class="inbox__title">New Messages(<span>{{unreadCount}}</span>)</h3>
      <ul class="messages">
        {% for message in messageRequests %}
          {% if message.is_read == False %}
            <li class="message message--unread">
          {% else %}
            <li class="message">
          {% endif %}
            <a href="{% url 'message' message.id %}">
              <span class="message__author">{{message.name}}</span>
              <span class="message__subject">{{message.subject}}</span>
              <span class="message__date">{{message.created}}</span>
            </a>
          </li>
    

        {% endfor %}
      </ul>
    </div>
</main>

{% endblock%}

users/templates/users/login-register.html
{% extends 'main.html' %}
{% load static %}

{% block body %}

{% if page == 'register' %}
    <div class="auth">
        <div class="card">
            <div class="auth__header text-center">
                <a href="/">
                    <img src="{% static 'images/icon.svg' %}" alt="icon" />
                </a>
                <h3>Register an Account</h3>
                <p>Create a new developer account</p>
            </div>

            <form action="{% url 'register' %}" method="POST" class="form auth__form">
                {% csrf_token %}

                {% for field in form %}
                <div class="form__field">
                    <label for="formInput#text">{{ field.label }}</label>
                    {{ field }}

                    {% for error in field.errors %}
                        <p style="color:red"> {{ error }} </>
                    {% endfor %}
                </div>
                {% endfor %}
               
                <div class="auth__actions">
                    <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
                </div>

            </form>
            <div class="auth__alternative">
                <p>Already have an Account?</p>
                <a href="{% url 'login' %}">Log In</a>
            </div>
        </div>
      </div>

{% else %}

    <div class="auth">
        <div class="card">
            <div class="auth__header text-center">
            <a href="/">
                <img src="{% static 'images/icon.svg' %}" alt="icon" />
            </a>
            <h3>Account Login</h3>
            <p>Hello Developer, Welcome Back!</p>
            </div>

            <form method="POST" action="" class="form auth__form">
                {% csrf_token %}
                <!-- Input:Email -->
                <div class="form__field">
                    <label for="formInput#text">Username: </label>
                    <input
                    class="input input--text"
                    id="formInput#text"
                    type="text"
                    name="username"
                    placeholder="Enter your username..."
                    />
                </div>

                <!-- Input:Password -->
                <div class="form__field">
                    <label for="formInput#password">Password: </label>
                    <input
                    class="input input--password"
                    id="formInput#passowrd"
                    type="password"
                    name="password"
                    placeholder="••••••••"
                    />
                </div>
                <div class="auth__actions">
                    <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
                    <a href="{% url 'reset_password' %}">Forget Password?</a>
                </div>
            </form>
            <div class="auth__alternative">
            <p>Don’t have an Account?</p>
            <a href="{% url 'register' %}">Sign Up</a>
            </div>
        </div>
    </div>

{% endif %}

{% endblock %}

users/templates/users/message.html
{% extends 'main.html' %}

{% block body %}
  <main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="{% url 'inbox' %}"><i class="fa-solid fa-chevron-left"></i></a>
        <h2 class="message__subject">{{message.subject}}</h4>
          {% if message.sender %}
            <a href="{% url 'user-profile' message.sender.id %}" class="message__author">{{message.name}}</a>
          {% else %}
          <p class="message__author">{{message.name}}</p>
          {% endif %}
          <p class="message__date">{{message.created}}</p>
          <div class="message__body">
            {{message.body|linebreaksbr}}
          </div>
      </div>
    </div>
  </main>
{% endblock %}

users/templates/users/profile-form.html
{% extends 'main.html' %}

{% block body %}

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'user-account' %}"><i class="fa-solid fa-chevron-left"></i></a>
            <br>
            <h1>Edit Account</h1>

                <form class="form" method="POST" action="{% url 'edit-account' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- Input:Text -->

                    {% for field in form %}
                    <div class="form__field">

                        <label for="formInput#text">{{field.label}}</label>
                        {{field}}
                        
                    </div>

                    {% endfor %}
                    
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>

{% endblock %}

users/templates/users/user-profile.html
{% extends 'main.html' %}

{% block body %}

    <main class="profile my-md">
        <div class="container">
            <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                <div class="card__body dev">
                    <img class="avatar avatar--xl" src="{{profile.imageURL}}" />
                    <h2 class="dev__name">{{profile.name}}</h2>
                    <p class="dev__title">{{profile.short_intro}}</p>
                    <p class="dev__location">{{profile.location}}</p>
                    <ul class="dev__social">

                    {% if profile.social_github %}
                        <li>
                            <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="fa-brands fa-github fa-2x"></i></a>
                        </li>
                    {% endif %}

                    {% if profile.social_twitter %}
                        <li>
                        <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="fa-brands fa-twitter fa-2x"></i></a>
                        </li>
                    {% endif %}

                    {% if profile.social_linkedin %}
                        <li>
                        <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="fa-brands fa-linkedin fa-2x"></i></a>
                        </li>
                    {% endif %}

                    {% if profile.social_website %}
                        <li>
                        <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="fa-solid fa-globe fa-2x"></i></a>
                        </li>
                    {% endif %}

                    </ul>
                    {% if request.user.profile.id != profile.id %}
                        <a href="{%url 'create-message' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
                    {% endif %}
                </div>
                </div>
            </div>
            <div class="column column--2of3">
                <div class="devInfo">
                <h3 class="devInfo__title">About Me</h3>
                <p class="devInfo__about">
                    {{profile.bio|linebreaksbr}}
                </p>
                </div>
                <div class="devInfo">
                <h3 class="devInfo__title">Skills</h3>
                <div class="devInfo__skills">

                    {% for skill in topSkills %}
                        <div class="devSkill">
                            <h4 class="devSkill__title">{{skill.name}}</h4>
                            <p class="devSkill__info">
                                {{skill.description}}
                            </p>
                        </div>
                    {% endfor %}

                    
                    <h3 class="devInfo__subtitle">Other Skills</h3>
                    <div class="devInfo__otherSkills">
                        {% for skill in otherSkills %}
                            <span class="tag tag--pill tag--sub tag--lg">
                                <small>{{skill.name}}</small>
                            </span>
                        {% endfor %}
                    </div>
                </div>
                </div>
                <div class="devInfo">
                <h3 class="devInfo__title">Projects</h3>
                <div class="grid grid--two">

                    {% for project in profile.project_set.all %}
                        <div class="column">
                            <div class="card project">
                                <a href="{% url 'project' project.id %}" class="project">
                                    <img class="project__thumbnail" src="{{project.imageURL.url}}" alt="project thumbnail" />
                                    <div class="card__body">
                                    <h3 class="project__title">{{project.title}}</h3>
                                    <p><a class="project__author" href="{% url 'user-profile' project.owner.id %}">{{project.owner.name}}</a></p>
                                    <p class="project--rating">
                                        <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Postitive
                                        Feedback ({{project.vote_total}} Votes)
                                    </p>
                                    <div class="project__tags">
                                        {% for tag in project.tags.all %}
                                            <span class="tag tag--pill tag--main">
                                                <small>{{tag}}</small>
                                            </span>
                                        {% endfor %}
                                    </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                </div>
            </div>
            </div>
        </div>
    </main>
{% endblock %}